# Generated by Django 2.2.6 on 2019-10-17 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_id_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='タイトル')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='入社日')),
            ],
            options={
                'db_table': 'User_id_table',
            },
        ),
    ]
